---
  extends: airbnb-base
  rules:
    semi: 0
    no-console: 0
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures: 
      modules: true
